spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8001

basic:
  credentials:
    username: ${BASIC_CREDENTIALS_USER}
    password: ${BASIC_CREDENTIALS_PASSWORD}
