DB_URL: jdbc:mysql://localhost:3306/identity_service
DB_USER: root
DB_PASSWORD: root

API_DOCS_OAUTH2_AUTH_URL: http://localhost:8001/oauth2/authorize
API_DOCS_OAUTH2_TOKEN_URL: http://localhost:8001/oauth2/token
API_DOCS_SERVER: http://localhost:8888/identity

API_DOCS_SECURITY_BASIC_USER: docs
API_DOCS_SECURITY_BASIC_PASSWORD: docs

INTERNAL_NOTIFICATION_SERVICE_CREDENTIALS_USER: user
INTERNAL_NOTIFICATION_SERVICE_CREDENTIALS_PASSWORD: password

INTERNAL_CREDIT_SERVICE_CREDENTIALS_USER: user
INTERNAL_CREDIT_SERVICE_CREDENTIALS_PASSWORD: password

OPENFEIGN_HC5_ENABLED: false
FEIGN_CLIENT_NOTIFICATION_CONNECT_TIMEOUT: 5000
FEIGN_CLIENT_NOTIFICATION_READ_TIMEOUT: 20000

JWT_PUBLIC_KEY_PATH: ./keys/jwt-public-key.pem
JWT_PRIVATE_KEY_PATH: ./keys/jwt-private-key.pem
JWT_AUTO_KEYGEN: false
JWT_KEY_ID: dev-jwt-external

API_DOCS_SECURITY_ENABLED: false
