API_DOCS_OAUTH2_AUTH_URL: http://localhost:8001/oauth2/authorize
API_DOCS_OAUTH2_TOKEN_URL: http://localhost:8001/oauth2/token
API_DOCS_SERVER: http://localhost:8888/notification

API_DOCS_SECURITY_BASIC_USER: docs
API_DOCS_SECURITY_BASIC_PASSWORD: docs

BASIC_CREDENTIALS_USER: user
BASIC_CREDENTIALS_PASSWORD: password

MONGO_DB_URI: mongodb://root:password@localhost:27017/notification_service?authSource=admin

DB_URL: jdbc:mysql://localhost:3306/notification_service
DB_USER: root
DB_PASSWORD: root

KAFKA_BOOTSTRAP_SERVERS: localhost:9092

API_DOCS_SECURITY_ENABLED: false
