package com.ndk.purchase.enums;

public enum SagaStep {
  VERIFYING_CONTENT,
  CONTENT_VERIFIED,
  DEDUCTING_BUYER,
  BUYER_DEDUCTED,
  ADDING_COMMISSION,
  COMMISSION_ADDED,
  INCREMENTING_COUNT,
  COMPLETING,
  COMPLETED,
  COMPENSATING_REVERSE_COMMISSION,
  COMPENSATING_REFUND_BUYER,
  COMPENSATION_COMPLETED,
  FAILED
}
