CREATE DATABASE IF NOT EXISTS identity_service;
CREATE DATABASE IF NOT EXISTS credit_service;
CREATE DATABASE IF NOT EXISTS content_service;
CREATE DATABASE IF NOT EXISTS notification_service;
CREATE DATABASE IF NOT EXISTS purchase_service;
CREATE DATABASE IF NOT EXISTS rating_service;
