server:
  port: 6969

spring:
  application:
    name: config-server
  profiles:
    include: native
  cloud:
    config:
      server:
        native:
          search-locations: ${CONFIG_SEARCH_LOCATIONS:file:/app/configs,file:./configs,file:./config-server/configs}
